export const MedicalItems = [
	{
		id: 1,
		shortName: 'standard-wheelchair',
		name: 'Standard Wheelchair',
		unitCost: 500,
		requested: 0,
		totalCost: 0,
		y: 643,
	},
	{
		id: 2,
		shortName: 'lightweight-wheelchair-multi-function',
		name: 'Lightweight Wheelchair Multi Function',
		unitCost: 1500,
		requested: 0,
		totalCost: 0,
		y: 620,
	},
	{
		id: 3,
		shortName: 'walking-frame',
		name: 'Walking Frame',
		unitCost: 210,
		requested: 0,
		totalCost: 0,
		y: 600,
	},
	{
		id: 4,
		shortName: 'Adult Diaper',
		name: 'Adult Diaper',
		unitCost: 23,
		requested: 0,
		totalCost: 0,
		y: 580,
	},
	{
		id: 5,
		shortName: 'nebulizer',
		name: 'Nebulizer',
		unitCost: 750,
		requested: 0,
		totalCost: 0,
		y: 560,
	},
	{
		id: 6,
		shortName: 'artificial-limb',
		name: 'Artificial Limb',
		unitCost: 8000,
		requested: 0,
		totalCost: 0,
		y: 540,
	},
	{
		id: 7,
		shortName: 'ripple-mattress',
		name: 'Ripple Mattress',
		unitCost: 750,
		requested: 0,
		totalCost: 0,
		y: 520,
	},
	{
		id: 8,
		shortName: 'oxygen-concentrator',
		name: 'Oxygen Concentrator',
		unitCost: 6000,
		requested: 0,
		totalCost: 0,
		y: 495,
	},
	{
		id: 9,
		shortName: 'suction-pump-machine',
		name: 'Suction Pump Machine',
		unitCost: 900,
		requested: 0,
		totalCost: 0,
		y: 470,
	},
	{
		id: 10,
		shortName: 'hearing-aid',
		name: 'Hearing Aid',
		unitCost: 2860,
		requested: 0,
		totalCost: 0,
		y: 446,
	},
	{
		id: 11,
		shortName: 'blood-pressure-set',
		name: 'Blood Pressure Set',
		unitCost: 400,
		requested: 0,
		totalCost: 0,
		y: 420,
	},
	{
		id: 12,
		shortName: 'glucometer-set',
		name: 'Glucometer Set',
		unitCost: 300,
		requested: 0,
		totalCost: 0,
		y: 395,
	},
	{
		id: 13,
		shortName: 'cpap-machine',
		name: 'Cpap Machine',
		unitCost: 7000,
		requested: 0,
		totalCost: 0,
		y: 375,
	},
	{
		id: 14,
		shortName: 'aero-chamber-child',
		name: 'Aero Chamber (Child)',
		unitCost: 100,
		requested: 0,
		totalCost: 0,
		y: 352,
	},
	{
		id: 15,
		shortName: 'aero-chamber-adult',
		name: 'Aero Chamber (Adult)',
		unitCost: 110,
		requested: 0,
		totalCost: 0,
		y: 330,
	},
	{
		id: 16,
		shortName: 'hand-sanitizer',
		name: 'Hand Sanitizer',
		unitCost: 35,
		requested: 0,
		totalCost: 0,
		y: 305,
	},
	{
		id: 17,
		shortName: 'hand-glove',
		name: 'Handle Glove',
		unitCost: 30,
		requested: 0,
		totalCost: 0,
		y: 280,
	},
	{
		id: 18,
		shortName: 'face-mask',
		name: 'Face Mask',
		unitCost: 70,
		requested: 0,
		totalCost: 0,
		y: 258,
	},
	{
		id: 19,
		shortName: 'infrared-forehead-thermometer',
		name: 'Infared Forehead Thermometer',
		unitCost: 270,
		requested: 0,
		totalCost: 0,
		y: 238,
	},
];
